version : '3'

services:
  php-composer:
    build: ./php
    image: php-composer:latest
    container_name: php-composer
    hostname: "pemrogramanweb-php-composer"
    volumes:
      - ./src:/var/www/html
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    working_dir: /var/www/html

  nginx:
    build: ./nginx
    image: nginx:latest
    container_name: nginx
    hostname: "pemrogramanweb-nginx"
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-composer

      