version : '3'
services:
  pemrogramanweb:
    build: ./php
    image: pemrogramanweb:latest
    container_name: pemrogramanweb
    hostname: "pemrogramanweb"
    volumes:
      - ./src:/var/www/html
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    working_dir: /var/www/html

  pemrogramanweb-nginx:
    build: ./nginx
    image: pemrogramanweb-nginx:latest
    container_name: pemrogramanweb-nginx
    hostname: "pemrogramanweb-nginx"
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - pemrogramanweb