version : '3'

services:

  pemrograman-web-database:
    image: mariadb:10.2
    container_name: mariadb
    restart: unless-stopped
    tty: true
    ports:
      - "33306:3306"
    volumes:
      - ./mariadb:/var/lib/mysql
      - ./conf.d:/etc/mysql/conf.d:ro
    environment:
      MYSQL_USER: actiangent
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Jakarta
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql